# menu
author: kriry # 作者
description: "kriry's world"
keyword: # seo keyword
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# donate
donate: true

# comment
# you can set gitment or uyan
comment: gitment

# gitment
gitment_owner: krircc
gitment_repo: krircc.github.io
gitment_oauth_id: fa541fea53a0e03f7cae
gitment_oauth_secret: d0875e9546bcf231f7f7de67f3ed2b7b6f070964

baidu_id: 

about:
  banner: http://file.muyutech.com/about.jpg
  avatar: https://raw.githubusercontent.com/krircc/krircc.github.io/kriry/themes/kriry/source/css/images/kriry.jpg
  description: 
